import numpy as np
from typing import List, Any

class IMMFilter:
    x_out: np.ndarray
    P_out: np.ndarray
    mu: np.ndarray

    def __init__(self, noise_cv: float, noise_ca: float, meas_noise: float) -> None: ...
    def predict(self, dt: float) -> None: ...
    def update(self, z_x: float, z_y: float, dt: float) -> None: ...

class KalmanFilter6D:
    P: np.ndarray
    x: np.ndarray
    estimated_speed_mps: float

    def __init__(self, init_easting: float, init_northing: float, init_alt: float) -> None: ...
    def step_oosm(self, timestamp: float, easting: float, northing: float, alt: float, noise_std_m: float, current_time: float) -> None: ...
    def step(self, easting_meas: float, northing_meas: float, alt_meas: float, dt: float, noise_std_m: float = 2.0) -> tuple[float, float, float]: ...
    def predict(self, dt: float) -> None: ...
    def compute_mahalanobis_oosm(self, meas_e: float, meas_n: float, meas_alt: float, meas_time: float, noise_std_m: float) -> float: ...
    def compute_mahalanobis_distance(self, easting_meas: float, northing_meas: float, alt_meas: float, noise_std_m: float) -> float: ...
    def update(self, easting_meas: float, northing_meas: float, alt_meas: float, noise_std_m: float = 2.0) -> None: ...
    def project_future(self, steps: int, dt: float) -> list[tuple[float, float, float]]: ...
    def get_P(self) -> np.ndarray: ...
    def get_x(self) -> np.ndarray: ...

class GeofenceEngine:
    def __init__(self) -> None: ...
    def add_zone(self, name: str, e: float, n: float, r: float, floor: float, ceil: float) -> None: ...
    def check_breaches(self, drone_id: str, easting: float, northing: float, alt: float, P: np.ndarray) -> List[str]: ...
